services:
  mysql:
      image: mysql:latest
      container_name: undercontroll-mysql
      restart: always
      hostname: localhost
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - "3306:3306"
  rabbitmq:
    image: rabbitmq-management-alpine
    container_name: undercontroll-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/

volumes:
  mysql_data:
  rabbitmq_data: